# Generated by Django 6.0.3 on 2026-04-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminlogins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryimage', models.ImageField(upload_to='packages/')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('register_id', models.CharField(max_length=10)),
                ('package_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('persons', models.IntegerField()),
                ('contact', models.CharField(max_length=10)),
                ('reject', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('CANCEL_request', models.CharField(default='no', max_length=20)),
                ('cancel_REASON', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enquiry_id', models.IntegerField()),
                ('persons', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('transactional_ID', models.CharField(max_length=30)),
                ('payment_MODE', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tourpackages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='packages/')),
                ('placename', models.CharField(max_length=25)),
                ('actual_PRICE', models.IntegerField()),
                ('special_price', models.IntegerField()),
                ('days', models.CharField(max_length=20)),
                ('travel_mode', models.CharField(max_length=20)),
                ('slots', models.IntegerField()),
                ('tour_themes', models.CharField(max_length=100)),
            ],
        ),
    ]
