# Generated by Django 6.0.3 on 2026-05-24 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tourpackages')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.register')),
            ],
        ),
    ]
