# Generated by Django 6.0.3 on 2026-05-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='addreview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
