# Generated by Django 6.0.3 on 2026-05-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_addreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='addreview',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.tourpackages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addreview',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.register'),
            preserve_default=False,
        ),
    ]
