# Generated by Django 6.0.3 on 2026-05-29 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_addreview_product_id_addreview_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.register'),
            preserve_default=False,
        ),
    ]
