# Generated by Django 6.0.3 on 2026-05-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_enquiry_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='user_id',
        ),
    ]
