# Generated by Django 6.0.3 on 2026-05-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_enquiry_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='register_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.register'),
        ),
    ]
