# Generated by Django 6.0.3 on 2026-07-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_enquiry_register_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='register_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.register'),
            preserve_default=False,
        ),
    ]
